#ifndef BOOT_MENU_LOGIC_H
#define BOOT_MENU_LOGIC_H

typedef unsigned char u8;
typedef unsigned short u16;
typedef unsigned int u32;

enum {
    BOOT_INFO_ADDR = 0x0500u,
    BOOT_INFO_EXTRA_FLAGS_ADDR = 0x050Cu,
    BOOT_INFO_WINDOWS_FLAGS_ADDR = 0x050Du,
    BOOT_INFO_WINDOWS_DRIVE_ADDR = 0x050Eu,
    MBR_SECTOR_ADDR = 0x0600u,
    GPT_HEADER_ADDR = 0x0800u,
    GPT_ENTRY_SECTOR_ADDR = 0x0A00u,
    CHILD_INODE_SECTOR_ADDR = 0x0C00u,
    CHILD_DIR_SECTOR_ADDR = 0x0E00u,
    GRANDCHILD_INODE_SECTOR_ADDR = 0x1200u,
    GRANDCHILD_DIR_SECTOR_ADDR = 0x1400u,
    CONFIG_FILE_INODE_SECTOR_ADDR = 0x1600u,
    LINUX_KERNEL_SECTOR_ADDR = 0x1800u,
    LINUX_INITRD_SECTOR_ADDR = 0x1C00u,
    FAT_EFI_DIR_SECTOR_ADDR = 0x2000u,
    FAT_EFI_BOOT_DIR_SECTOR_ADDR = 0x2200u,
    FAT_EFI_SYSTEMD_DIR_SECTOR_ADDR = 0x2400u,
    FAT_EFI_BOOT_FILE_SECTOR_ADDR = 0x2600u,
    FAT_EFI_SYSTEMD_FILE_SECTOR_ADDR = 0x2800u,
    WINDOWS_PROBE_MBR_ADDR = 0x2A00u,
    WINDOWS_PROBE_GPT_HEADER_ADDR = 0x2C00u,
    WINDOWS_PROBE_GPT_ENTRY_SECTOR_ADDR = 0x2E00u,
    WINDOWS_PROBE_ESP_VBR_ADDR = 0x3000u,
    WINDOWS_PROBE_DATA_VBR_ADDR = 0x3200u,
    CHAINLOAD_BUFFER_ADDR = 0x7E00u,
    BOOT_TARGET_LINUX = 0x01u,
    BOOT_TARGET_WINDOWS = 0x02u,
    BOOT_INFO_FLAG_MBR_VALID = 0x01u,
    BOOT_INFO_FLAG_GPT_HEADER_VALID = 0x02u,
    BOOT_INFO_FLAG_GPT_ENTRY_VALID = 0x04u,
    BOOT_INFO_FLAG_CHAINLOAD_MATCH = 0x08u,
    BOOT_INFO_FLAG_CHAINLOAD_READ_OK = 0x10u,
    BOOT_INFO_FLAG_LINUX_LAYOUT_VALID = 0x20u,
    BOOT_INFO_FLAG_ROOT_DIR_VALID = 0x40u,
    BOOT_INFO_FLAG_CHILD_DIR_VALID = 0x80u,
    BOOT_INFO_DETAIL_GRUB_DIR_VALID = 0x01u,
    BOOT_INFO_DETAIL_GRUB_CFG_VALID = 0x02u,
    BOOT_INFO_DETAIL_FAT_ENTRIES_VALID = 0x04u,
    BOOT_INFO_DETAIL_FAT_ENTRY_FILE_VALID = 0x08u,
    BOOT_INFO_DETAIL_FAT_KERNEL_VALID = 0x10u,
    BOOT_INFO_DETAIL_FAT_INITRD_VALID = 0x20u,
    BOOT_INFO_EXTRA_FAT_EFI_DIR_VALID = 0x01u,
    BOOT_INFO_EXTRA_FAT_EFI_BOOT_DIR_VALID = 0x02u,
    BOOT_INFO_EXTRA_FAT_EFI_SYSTEMD_DIR_VALID = 0x04u,
    BOOT_INFO_EXTRA_FAT_EFI_BOOT_FILE_VALID = 0x08u,
    BOOT_INFO_EXTRA_FAT_EFI_SYSTEMD_FILE_VALID = 0x10u,
    BOOT_INFO_WINDOWS_FLAG_MBR_VALID = 0x01u,
    BOOT_INFO_WINDOWS_FLAG_GPT_HEADER_VALID = 0x02u,
    BOOT_INFO_WINDOWS_FLAG_GPT_ENTRY_VALID = 0x04u,
    BOOT_INFO_WINDOWS_FLAG_ESP_VBR_VALID = 0x08u,
    BOOT_INFO_WINDOWS_FLAG_DATA_VBR_VALID = 0x10u
};

typedef struct BootInfo {
    u8 selected_target;
    u8 boot_drive;
    u8 inspection_flags;
    u8 detail_flags;
} BootInfo;

/*
 * The C side of the larger boot menu loader starts here after the
 * assembly entry point has set up a protected-mode stack.
 */
void boot_menu_main(void);

#endif /* BOOT_MENU_LOGIC_H */
